name: niaje
description: Voice assistant app powered by ChatGPT

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^3.6.2
  speech_to_text: ^6.1.1
  avatar_glow: ^2.0.2
  logger: ^1.1.0
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
